"""Repository contracts used by orchestration and application services."""

from typing import Protocol
from uuid import UUID

from interactive_forecasting.domain.models import (
    ArtifactManifest,
    ArtifactRef,
    ExperimentRun,
    Job,
    LLMCall,
    Message,
    Task,
)


class TaskRepositoryPort(Protocol):
    def create(self, task: Task) -> Task: ...
    def get(self, task_id: UUID) -> Task | None: ...
    def save(self, task: Task, *, expected_version: int) -> Task: ...
    def save_transition(self, task: Task, event: Message, *, expected_version: int) -> Task: ...


class MessageRepositoryPort(Protocol):
    def append(self, message: Message) -> bool: ...
    def get(self, message_id: UUID | None) -> Message | None: ...
    def list_for_task(self, task_id: UUID) -> list[Message]: ...
    def record_delivery(self, message_id: UUID, handler_name: str, status: str) -> None: ...
    def was_delivered(self, message_id: UUID, handler_name: str) -> bool: ...


class JobRepositoryPort(Protocol):
    def create(self, job: Job) -> Job: ...
    def get(self, job_id: UUID) -> Job | None: ...
    def save(self, job: Job) -> Job: ...


class ExperimentRepositoryPort(Protocol):
    def create(self, run: ExperimentRun) -> ExperimentRun: ...
    def get(self, run_id: UUID) -> ExperimentRun | None: ...
    def save(self, run: ExperimentRun, *, expected_version: int) -> ExperimentRun: ...


class ArtifactRepositoryPort(Protocol):
    def put_bytes(self, relative_uri: str, content: bytes) -> ArtifactRef: ...
    def read_bytes(self, reference: ArtifactRef) -> bytes: ...
    def write_manifest(self, manifest: ArtifactManifest) -> ArtifactRef: ...


class LLMCallRepositoryPort(Protocol):
    def create(self, call: LLMCall) -> LLMCall: ...
    def get(self, call_id: UUID) -> LLMCall | None: ...
    def list_for_task(self, task_id: UUID) -> list[LLMCall]: ...
